### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by djandrew2005** [williamcorsel/hassio-addons#18]
Can you update to the latest version of Minecraft server docker?

**Comment by williamcorsel** [comment]
You can adjust the container version in the build file: [hamc-server-java/build.yaml](https://github.com/williamcorsel/hassio-addons/blob/main/hamc-server-java/build.yaml).

I don't have the time to test if the latest version will work properly, but I welcome a PR or fork if you're willing to put in the time!
