### ISSUE TITLE
Bedrock server issues

### ISSUE THREAD

**Issue by MegaTheLEGEND** [williamcorsel/hassio-addons#8]
I have the Minecraft bedrock server running as a Home assistant add on. When I join the server on my phone I can't break or place any blocks farther than a small radius away from spawn. Mobs simply ignore me and they cannot be killed. Items cannot be picked up. It seemed to break right after a mincraft update. 

Edit: on the client, when I move away from where I spawned then try to teleport to myself it tp's me back to where I spawned. It seems to be able to interact with anything that is within spawn point view. I ran the itzg/mincraft-bedrock server in docker and it works fine.

-----------------------------------------------------------
 Add-on: HAMC Server Bedrock
 Host a Bedrock Minecraft server on Home Assistant
-----------------------------------------------------------
 Add-on version: 1.0.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.4  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.8.1
 Home Assistant Supervisor: 2023.07.1
-----------------------------------------------------------

**Comment by williamcorsel** [comment]
Thanks for reporting this issue. I indeed ran into the same problem. Let me know if the latest release fixed the issue for you.

**Comment by MegaTheLEGEND** [comment]
Unfortunately that update did not fix the issue.

**Comment by williamcorsel** [comment]
You could try to completely reinstall the extension. In addition, delete the server data folder `/addons/hamc-server-bedrock/data`. I couldn't reproduce the issue with the latest patch when I tried it.

**Comment by MegaTheLEGEND** [comment]
Deleting the data folder Indeed fixed the problem. Thank you!
